export type MockServerData = {
  cities: string[];
  coords: string[];
  descriptions: string[];
  features: string[];
  isFavorites: [boolean, boolean];
  isPremium: [boolean, boolean];
  numberComments: number[];
  numberGuests: number[];
  numberRooms: number[];
  photosHousing: string[];
  previewImages: string[];
  ratings: number[];
  titles: string[];
  typeHousing: string[];
  users: string[];
  avatar: string[];
  email: string[];
  userType: string[];
};
